micronaut:
  application:
    name: carrosGrpc

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=carros_test isolar ambientes
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '12345678'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true